version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "${FRONTEND_PORT}:80"
      - "${PORT}:5000"
      - "${WEBSOCKET_PORT}:5001"
    restart: unless-stopped
